### PR TITLE
clipping planes range fits geometry 

### PR DESCRIPTION
**Pull request by PWhiddy**

### CODE REVIEW

**Comment by PWhiddy** [comment]
Small question, in JSRootPainter.jquery.js I am trying to make the "focus" option available from the browser sidebar, but am having trouble finding the right context to call "focusCamera". I think it is simple but can you show me how I can access this method here?

**Comment by linev** [comment]
Hi Peter,
It is not in the JSRootPainter.jquery.js.
There is function in JSRootGeoPainter.js called JSROOT.GEO.expandList().
It is used to provide items for lists with TGeo-related objects (nodes, materials,...).
Such items are displayed in the browser. 
One could configure that such item get extra entries in the context menu.
Example you can find in JSROOT.GEO.expandVolume.
Probably, I provide preliminary code, which you can extend.

**Comment by bellenot** [comment]
The "Cutting range based on geomtry size" doesn't work properly. At least on z axis with the lhcb geometry (https://bellenot.web.cern.ch/bellenot/Public/GitHub/?json=../Latest/files/lhcb.json)

**Comment by linev** [comment]
@PWhiddy @bellenot 
At the moment some functions in geo painter may be broken, when JSON file is used.
For the moment I do all kind of tests and developments for TGeoManager. Like
[this link](http://jsroot.gsi.de/dev/?file=http://jsroot.gsi.de/files/geom/rootgeom.root&item=simple1&expand=simple1/Nodes/REPLICA_2).
Later I will adjust code for the JSON files as well.

**Comment by linev** [comment]
@PWhiddy 
Now there is function JSROOT.TGeoPainter.prototype.focusOnItem.
It is dedicated to make focus for selected item. 
It should appears as "Focus" command for the items from TGeoManager Nodes hierarchy (not in Volume).
For the moment I only calculate transformation matrix for the item and item dimension.
You should complete function.

**Comment by linev** [comment]
@PWhiddy @bellenot 
Actually, in "Cutting range based on geometry size" sign is wrong. Probably, only for Z axis. 
It could be nice seen in the hades geometry:
http://jsroot.gsi.de/dev/examples.htm?more#tgeo_hades

**Pull request merged**
