### PR TITLE
Clipping planes exist locally on materials

### PR DESCRIPTION
**Pull request by PWhiddy**
With the recent version of threejs, clipIntersection can be toggled at the material level. This allows JSRoot to use local clipping rather than global, so things like tracks, hits and axis labels don't have to be clipped.

### CODE REVIEW

**Comment by linev** [comment]
Hi Peter,

Does it normal three.js r82?
If yes, I need to update other three.js - related files.

Regards,
Sergey

**Comment by PWhiddy** [comment]
Yes this is normal three.js r82
The examples I tested, it all still seemed to work.
I'm not sure if the new module system is required, it appears there are two different build versions
https://github.com/mrdoob/three.js/tree/master/build
In this PR I replaced three.js with the one there

**Comment by linev** [comment]
Hi Peter,

I take released r82 version of three.js
I also switch to the minified version of three.js and three.extra.js scripts, 
while it makes significant difference in time for loading scripts.
I also adjust code concerning require.js - now it handled differently in three.js
Please check if changes are still working for you.

Regards,
Sergey

**Comment by PWhiddy** [comment]
Latest jsroot dev is working great, thanks Sergey!

Peter

**Pull request merged**
