### PR TITLE
Add missing streamer for TStreamerInfo::kCharStar (char *)

### PR DESCRIPTION
**Pull request by bellenot**

### CODE REVIEW

**Comment by linev** [comment]
Are there ROOT class with such data member?
Should I apply patch for master?

**Comment by bellenot** [comment]
Alice has one (at least), see for example [AliPerformanceObject](http://git.cern.ch/pubweb/AliPhysics.git/blob/HEAD:/PWGPP/TPC/AliPerformanceObject.h)

**Comment by bellenot** [comment]
P.S. I don't think is is needed in the master.
BTW, there are still issues when reading some Alice files (see [this example](https://bellenot.web.cern.ch/bellenot/Public/GitHub/?file=../Latest/alice/QAresults_barrel.root&item=TPC_PerformanceQA/TPCQA;1))

**Comment by linev** [comment]
Problem is fixed now - it was missing support of members like:

    TH1F *fhArr[3]; //-> several preallocated histograms

Now should work.

**Pull request merged**
