### PR TITLE
Empty meshes changed to object3D, fixed empty geometry error

### PR DESCRIPTION
**Pull request by PWhiddy**
Issue was caused by invisible meshes that had geometries with no vertices. Now meshes and geometries are only created when a visible geometry is being created. 
Not sure why this says it can't be automatically merged, perhaps I messing up getting changes from your dev branch?

### CODE REVIEW

**Comment by linev** [comment]
Peter, next time before submitting pull request merge your code with current code in dev branch.
Next days I plan to introduce several new features into geo painter

**Comment by PWhiddy** [comment]
My mistake, I thought I did but I guess something didn't commit correctly.

Which features are you planning on introducing?

**Comment by linev** [comment]
Enable/disable of visibility flags via hierarchy browser.
Idea to automatically update drawing when visibility flag changing.

**Comment by bellenot** [comment]
And BTW, once picking is working, we could consider changing those parameters via context menu on the shapes themselves...

**Comment by linev** [comment]
Picking is already done in the 3D histo drawing, therefore I see no problem to implement it in geo drawing.
Main problem is not toggling of visibility flags, but provide code to update three.js model.

**Pull request merged**
