### PR TITLE
New lighting and UI, bugfixes

### PR DESCRIPTION
**Pull request by PWhiddy**
Organized menu options and moved them to dat.gui 
New material look and option for SSAO shading.
"Advanced" settings as a place to stick parameters for easy tweaking
Fixed mouse intersection alignment and orbit controls centering after focusing

@bellenot I haven't figured out why setting clipping bounds from boundingBox is messing up the Z axis on some models yet, additionally now when smooth lighting is enabled and clipping is set below 0 for certain axes and model all rendering goes white. I think these issues are related, maybe having something to do with z and y axes being flipped in some cases? https://github.com/PWhiddy/jsroot/blob/master/scripts/JSRootGeoPainter.js#L1793

### CODE REVIEW

**Comment by linev** [comment]
Peter, Z-axis orientation for TGeo model differs from conventional.
Normally Z axis oriented in upside direction, but most detectors models build along horizontal beam line.
And in all such models beam-line direction is Z axis.
Therefore normally Y axis showing up when drawing TGeo (one can disable this option).

**Comment by linev** [comment]
@PWhiddy @bellenot 
There are several problems with your code.
   1. I need to fix several simple errors - code was trying to call several missing functions.
   2. After fixes I see nothing with CanvasRenderer.
   3. My Firefox crashes when starting any TGeo drawing.
Probably, CanvasRenderer can be fixed, but last problem is very difficult.
My Firefox runs in WebGL emulation mode (saying to JavaScript that WebGL supported but just emulating it). I guess, new code with shaders crashing the Firefox.

I have no idea how to proceed while I cannot debug code when it simply crashes. Can one provide version,
which disable all new features by default - at least as long as we find solution to detect that browser does not support them.

I also recommend always test code with CanvasRenderer.  You simply can specify 'webgl=0' option in URL string. Like:
http://jsroot.gsi.de/dev/?nobrowser&file=../files/geom/rootgeom.root&item=simple1;1&webgl=0

I revert code and suggest that you fix all these problems before providing new pull request

**Comment by linev** [comment]
About shaders - I add them into three.extra.js. They seems to be small.

**Comment by linev** [comment]
That about idea already now switch to three.js r 79?

**Comment by PWhiddy** [comment]
At first I was very puzzled to figure out why it was crashing so badly for
you.
One of the changes I made last week for clipping was with shader code, so I
assumed canvas/emulator was okay with that. But something about these new
shaders it has trouble with I guess.

The missing function that kept getting called was the getSize function,
which exists for WebGLRenderer but not CanvasRenderer apparently.

I discovered also that the reason nothing was rendering was because I
switched the material for volumes from MeshLambert to the newer
MeshStandard material. I didn't know at the time, but it's not supported by
canvas renderer either.
I can revert this, or try to make a catch for webgl in rootgeobase that
sets material based on renderer.
If you were not able to see it, here's how drawing looks with standard
material and ssao option compared to original


​​​
​

Also, as for updating threejs -- switching to r79 would be fine, although
if you want me to submit a pull request to them for clipping option still,
when it is merged it will probably be only in their dev version until next
major release (could be weeks or maybe a month or two).

**Comment by linev** [comment]
That is important - all your new features should be optional and by default all such options should be off.
Only this way we can go further. Once we understand why it crashes (which option), we could try to add protection. 

Support of CanvasRenderer is essential. One could request to add missing getSize function to three.js (I also saw it yesterday).

**Comment by bellenot** [comment]
BTW, Z axis clipping is still not working properly...

**Comment by linev** [comment]
It may happen, that you are using minified version of three.js script (look into you index.htm file).
It is not patched.

In any case, I plan to upgrade three.js to r79 anyway.
I guess, the only way for us - is to get patch into three.js repository.

**Pull request merged**
