### PR TITLE
Use histogram fMinimum/fMaximum for lego plot (3D) Z axis range when …

### PR DESCRIPTION
**Pull request by bellenot**
…needed

### CODE REVIEW

**Comment by linev** [comment]
Is it not better to assign zmin/zmax values directly when drawing 3D axes?
It is function JSROOT.Painter.TH2Painter_Draw3D.

**Comment by linev** [comment]
That is also missing - drawing labels instead of number for the axes in 3D

**Comment by bellenot** [comment]
Well, it is not complete anyway, since the bins with 0 entries are not drawn in 3D mode. So there is still some development to be done for lego plots...

**Comment by linev** [comment]
Do you want to implement this?
It also can go into master branch.
I want to finish code for TGeo drawing, probably later today I can check lego plot myself.

**Comment by bellenot** [comment]
I wish I could, but I'll be away later today...

**Comment by linev** [comment]
Ok, I will check later today.

**Comment by bellenot** [comment]
See also the lego2 option (for later):
canvas_1

**Comment by linev** [comment]
I am aware about this draw option.
Till now I have no good solution for this.
Most probably, one could create special colz textures and to use them.
Like described here:

http://solutiondesign.com/blog/-/blogs/webgl-and-three-js-texture-mappi-1/

But this is not an easy task.

**Comment by bellenot** [comment]
I know, but this is not urgent anyway, I'll take a look for possible solutions sometime in the future

**Comment by bellenot** [comment]
See also: https://stemkoski.github.io/Three.js/#graphulus-surface

**Comment by linev** [comment]
In current code I add support of the labels in 3D plots:
http://jsroot.gsi.de/dev/?nobrowser&json=http://jsroot.gsi.de/files/tmp/th2.json.gz&opt=lego

**Comment by bellenot** [comment]
Excellent! Thanks! I forgot to look at this...

**Comment by bellenot** [comment]
BTW, will those changes also be applied in the master?

**Comment by linev** [comment]
> BTW, will those changes also be applied in the master?
Not yet - these are significant changes/improvements, not a bug fix.
I prefer to keep them in 'dev' branch and release with 4.6.0 version in several weeks

**Comment by bellenot** [comment]
OK, fine with me

**Comment by linev** [comment]
Now there is support of several lego draw options like: lego0, lego2, legofb, legobb.
For instance, same th2 histogram with lego2 plot:

pad

Or via URL:

http://jsroot.gsi.de/dev/?json=http://jsroot.gsi.de/files/tmp/th2.json.gz&opt=lego2,pal50,gridz

LEGO drawing now implemented with pure BufferArray. I use extra index array to assign each vertex with histogram bin number, therefore I do not need normal geometry model for that. Still missing - highlight of the bins in such model, but this can be done separately.
I plan to implement TH3 drawing with the same approach.

**Comment by linev** [comment]
With latest changes produced picture is very close to the original one:
http://jsroot.gsi.de/dev/?json=../files/th2ul.json.gz&opt=lego2,pal50

**Pull request merged**
