### PR TITLE
Implement minimal RequireJS functionality

### PR DESCRIPTION
**Pull request by bellenot**
- add require.js and main.js (needed by RequireJS)
- make use of RequireJS in a backward compatible way (can still be used without RequireJS)
- only minimal changes have been made, since the correct way would require a complete restructuring of the code

### CODE REVIEW

**Comment by bellenot** [comment]
And you can test it and check that everything is backward compatible

**Comment by linev** [comment]
I will check it soon.
Most probably, JSROOT.AssertPrerequisities could be done even simpler.

**Comment by bellenot** [comment]
Probably, I just didn't want to touch it too much...

**Comment by linev** [comment]
I also did many changes in my local repository.
Let see how it can be merged - I need several hours to complete.

**Comment by bellenot** [comment]
No problem, take your time

**Pull request merged**
