### PR TITLE
Tried to simplify things and then conflicted with your latest changes...

### PR DESCRIPTION
**Pull request by bellenot**

### CODE REVIEW

**Comment by linev** [comment]
I will only rename 'THREE' -> "three.min" and "JSRootIO" -> "JSRootIOEvolution"

About configuration via main.js - I will check how it can be done better.
Probably one should introduce it back.

**Comment by bellenot** [comment]
There is something weird... How can my fork be:
This branch is 11 commits ahead, 1 commit behind linev:master?

**Comment by linev** [comment]
Sometime I also not understand information git shows.
1 commit behind  - seems to be my last modification some minutes ago.
11 commits ahead - these are all your commits which are not present directly in my repository.

**Comment by bellenot** [comment]
I don't think I have done 11 commits... Anyway, still performing tests and you can simplify the paths (see the diff I sent by mail)

**Comment by bellenot** [comment]
Oh wait, in fact the 11 commits are the two or three mines plus yours... Weird...

**Comment by linev** [comment]
I also has similar problems when working with root repository.
You never knows - are you in sync or not.
When you submitting my changes to the main repository I typically revert all my commits in local repository and then sync with master.

**Pull request closed without merging**
